language: python

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libpoppler-cpp-dev unpaper tesseract-ocr tesseract-ocr-eng

sudo: false

matrix:
    include:
        - python: 3.4
        - python: 3.5
        - python: 3.6
        - python: 3.6

install:
    - pip install --requirement requirements.txt

script:
    - cd src/
    - pytest --cov
    - pycodestyle

after_success:
    - coveralls
