language: python

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libpoppler-cpp-dev unpaper tesseract-ocr tesseract-ocr-eng

sudo: false

matrix:
    include:
        - python: 3.4
        - python: 3.5
        - python: 3.6

install:
    - pip install --requirement requirements.txt
    - pip install sphinx
script:
    - cd src/
    - pytest --cov
    - pycodestyle
    - sphinx-build -b html ../docs ../docs/_build -W

after_success:
    - coveralls
